apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"          # Fargate requires IP targets
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"      # public NLB
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"    # health check protocol
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"       # match app port
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: spring-boot-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
