name: java-maven-sonar-argocd-helm-k8s

on:
  push:
    branches:
      - main

env:
  APP_DIR: java-maven-sonar-argocd-helm-k8s/spring-boot-app
  MANIFEST_FILE: java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
  DOCKER_IMAGE: devenops641/springboot-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      #  Setup Java
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      #  Build & Test
      - name: Build and Test with Maven
        run: |
          cd $APP_DIR
          mvn clean package

      #  SonarQube Analysis
      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: http://44.211.160.25:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd $APP_DIR
          mvn sonar:sonar \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.host.url=$SONAR_HOST_URL

      #  Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build Docker Image
      - name: Build Docker Image
        run: |
          cd $APP_DIR
          docker build -t $DOCKER_IMAGE:${{ github.run_number }} .

      #  Push Docker Image
      - name: Push Docker Image
        run: |
          docker push $DOCKER_IMAGE:${{ github.run_number }}

      #  Update Deployment YAML
      - name: Update Deployment File
        run: |
          git config --global user.email "abhishek.xyz@gmail.com"
          git config --global user.name "Abhishek Veeramalla"

          sed -i "s/replaceImageTag/${{ github.run_number }}/g" $MANIFEST_FILE

          git add $MANIFEST_FILE
          git commit -m "Update deployment image to version ${{ github.run_number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
